function [k11,k12,k13,k22,k23,k33,dk11_dlnkperp,dk12_dlnkperp,dk13_dlnkperp,dk22_dlnkperp,dk23_dlnkperp,dk33_dlnkperp,dk11_dlnkpar,dk12_dlnkpar,dk13_dlnkpar,dk22_dlnkpar,dk23_dlnkpar,dk33_dlnkpar,dk11_dv1,dk12_dv1,dk13_dv1,dk22_dv1,dk23_dv1,dk33_dv1,dk11_dv2,dk12_dv2,dk13_dv2,dk22_dv2,dk23_dv2,dk33_dv2,dk11_dv3,dk12_dv3,dk13_dv3,dk22_dv3,dk23_dv3,dk33_dv3] = uniax2tensor_auto_optimized(lnkperp,lnkpar,v1,v2,v3)
%UNIAX2TENSOR_AUTO_OPTIMIZED
%    [K11,K12,K13,K22,K23,K33,DK11_DLNKPERP,DK12_DLNKPERP,DK13_DLNKPERP,DK22_DLNKPERP,DK23_DLNKPERP,DK33_DLNKPERP,DK11_DLNKPAR,DK12_DLNKPAR,DK13_DLNKPAR,DK22_DLNKPAR,DK23_DLNKPAR,DK33_DLNKPAR,DK11_DV1,DK12_DV1,DK13_DV1,DK22_DV1,DK23_DV1,DK33_DV1,DK11_DV2,DK12_DV2,DK13_DV2,DK22_DV2,DK23_DV2,DK33_DV2,DK11_DV3,DK12_DV3,DK13_DV3,DK22_DV3,DK23_DV3,DK33_DV3] = UNIAX2TENSOR_AUTO_OPTIMIZED(LNKPERP,LNKPAR,V1,V2,V3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    29-Aug-2026 14:33:57

t2 = exp(lnkpar);
t3 = exp(lnkperp);
t4 = v1.^2;
t5 = v2.^2;
t6 = v3.^2;
t7 = -t3;
t8 = t2+t7;
k11 = t3+t4.*t8;
if nargout > 1
    t9 = t8.*v1;
    k12 = t9.*v2;
end
if nargout > 2
    k13 = t9.*v3;
end
if nargout > 3
    k22 = t3+t5.*t8;
end
if nargout > 4
    t10 = t8.*v2;
    k23 = t10.*v3;
end
if nargout > 5
    k33 = t3+t6.*t8;
end
if nargout > 6
    dk11_dlnkperp = t3+t4.*t7;
end
if nargout > 7
    dk12_dlnkperp = t7.*v1.*v2;
end
if nargout > 8
    dk13_dlnkperp = t7.*v1.*v3;
end
if nargout > 9
    dk22_dlnkperp = t3+t5.*t7;
end
if nargout > 10
    dk23_dlnkperp = t7.*v2.*v3;
end
if nargout > 11
    dk33_dlnkperp = t3+t6.*t7;
end
if nargout > 12
    dk11_dlnkpar = t2.*t4;
end
if nargout > 13
    dk12_dlnkpar = t2.*v1.*v2;
end
if nargout > 14
    dk13_dlnkpar = t2.*v1.*v3;
end
if nargout > 15
    dk22_dlnkpar = t2.*t5;
end
if nargout > 16
    dk23_dlnkpar = t2.*v2.*v3;
end
if nargout > 17
    dk33_dlnkpar = t2.*t6;
end
if nargout > 18
    dk11_dv1 = t9.*2.0;
end
if nargout > 19
    dk12_dv1 = t10;
end
if nargout > 20
    t11 = t8.*v3;
    dk13_dv1 = t11;
end
if nargout > 21
    dk22_dv1 = 0.0;
end
if nargout > 22
    dk23_dv1 = 0.0;
end
if nargout > 23
    dk33_dv1 = 0.0;
end
if nargout > 24
    dk11_dv2 = 0.0;
end
if nargout > 25
    dk12_dv2 = t9;
end
if nargout > 26
    dk13_dv2 = 0.0;
end
if nargout > 27
    dk22_dv2 = t10.*2.0;
end
if nargout > 28
    dk23_dv2 = t11;
end
if nargout > 29
    dk33_dv2 = 0.0;
end
if nargout > 30
    dk11_dv3 = 0.0;
end
if nargout > 31
    dk12_dv3 = 0.0;
end
if nargout > 32
    dk13_dv3 = t9;
end
if nargout > 33
    dk22_dv3 = 0.0;
end
if nargout > 34
    dk23_dv3 = t10;
end
if nargout > 35
    dk33_dv3 = t11.*2.0;
end
end
