function [A, Jac] = amplitude(T0tilde, Jac_T0tilde)
% Generated by ChatGPT must CHECK!
    A = abs(T0tilde);
    if nargout > 1
        Jac = real(conj(T0tilde(:)) .* Jac_T0tilde ./ A(:));
    end
end