function tests = test_RBFKernel()
    tests = functiontests(localfunctions);
end

function setupOnce(testCase)
    n = randi([3,9]); m = randi([5,13]); D = randi([2,4]);
    testCase.TestData.X = unifrnd(-10,10,n,D);
    testCase.TestData.Xp = unifrnd(-10,10,m,D);
    testCase.TestData.lnsigma = log(unifrnd(0.5,2,datasample([1,n], 1),1));
    testCase.TestData.lnsigmap = log(unifrnd(0.5,2,datasample([1,m], 1),1));
    testCase.TestData.lnell = log(unifrnd(5,15,1,1));
    testCase.TestData.options = optimoptions("fminunc", FiniteDifferenceType="central");

    timestamp = string(datetime("now", Format="uuuu-MM-dd_HH-mm-ss.SSS"));
    testCase.onFailure(@() logFailure(testCase, timestamp));
end

function teardownOnce(~)
end

function test_checkGradients_all_design_variables(testCase)
    Ns = length(testCase.TestData.lnsigma);
    Nsp = length(testCase.TestData.lnsigmap);
    x0 = [ ...
        testCase.TestData.lnsigma(:).', ...
        testCase.TestData.lnsigmap(:).', ...
        testCase.TestData.lnell ...
    ];
    if ~checkGradients(@(x) format_output_for_checkGradients(@RBFKernel,  ...
            testCase.TestData.X, ...
            testCase.TestData.Xp, ...
            DesignVariable( ...
                x(1:Ns), ...
                1:Ns, ...
                length(x0) ...
            ), ...
            DesignVariable( ...
                x(Ns+1:Ns+Nsp), ...
                Ns+1:Ns+Nsp, ...
                length(x0) ...
            ), ...
            DesignVariable( ...
                x(Ns+Nsp+1), ...
                Ns+Nsp+1, ...
                length(x0) ...
            ) ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_no_design_variables(testCase)
    x0 = [];
    if ~checkGradients(@(x) format_output_for_checkGradients(@RBFKernel,  ...
            testCase.TestData.X, ...
            testCase.TestData.Xp, ...
            testCase.TestData.lnsigma, ...
            testCase.TestData.lnsigmap, ...
            testCase.TestData.lnell ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_every_other_design_variables(testCase)
    Ns = length(testCase.TestData.lnsigma);    
    x0 = [testCase.TestData.lnsigma(:).', testCase.TestData.lnell(:).'];
    if ~checkGradients(@(x) format_output_for_checkGradients(@RBFKernel,  ...
            testCase.TestData.X, ...
            testCase.TestData.Xp, ...
            DesignVariable( ...
                x(1:Ns), ...
                1:Ns, ...
                length(x0) ...
            ), ...            
            testCase.TestData.lnsigmap, ...
            DesignVariable(x(Ns+1), Ns+1, length(x0)) ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_same_lnsigma(testCase)
    Ns = length(testCase.TestData.lnsigma);
    x0 = [testCase.TestData.lnsigma(:).', testCase.TestData.lnell(:).'];
    if ~checkGradients(@(x) format_output_for_checkGradients(@RBFKernel,  ...
            testCase.TestData.X, ...
            testCase.TestData.X, ...
            DesignVariable( ...
                x(1:Ns), ...
                1:Ns, ...
                length(x0) ...
            ), ...
            DesignVariable( ...
                x(1:Ns), ...
                1:Ns, ...
                length(x0) ...
            ), ...
            DesignVariable(x(Ns+1), Ns+1, length(x0)) ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end