function tests = test_RBFKernel()
    tests = functiontests(localfunctions);
end

function setupOnce(testCase)
    n = randi([3,9]); m = randi([5,13]); D = randi([2,4]);
    testCase.TestData.X = unifrnd(-10,10,n,D);
    testCase.TestData.Xp = unifrnd(-10,10,m,D);
    testCase.TestData.sigma = unifrnd(0.5,2,datasample([1,n], 1),1);
    testCase.TestData.sigmap = unifrnd(0.5,2,datasample([1,m], 1),1);
    testCase.TestData.l = unifrnd(5,15,1,1);
    testCase.TestData.options = optimoptions("fminunc", FiniteDifferenceType="central");

    timestamp = string(datetime("now", Format="uuuu-MM-dd_HH-mm-ss.SSS"));
    testCase.onFailure(@() logFailure(testCase, timestamp));
end

function teardownOnce(~)
end

function test_checkGradients_all_design_variables(testCase)
    Ns = length(testCase.TestData.sigma);
    Nsp = length(testCase.TestData.sigmap);
    x0 = [ ...
        testCase.TestData.sigma(:).', ...
        testCase.TestData.sigmap(:).', ...
        testCase.TestData.l ...
    ];
    if ~checkGradients(@(x) RBFKernel( ...
            testCase.TestData.X, ...
            testCase.TestData.Xp, ...
            DesignVariable( ...
                x(1:Ns), ...
                1:Ns, ...
                length(x0) ...
            ), ...
            DesignVariable( ...
                x(Ns+1:Ns+Nsp), ...
                Ns+1:Ns+Nsp, ...
                length(x0) ...
            ), ...
            DesignVariable( ...
                x(Ns+Nsp+1), ...
                Ns+Nsp+1, ...
                length(x0) ...
            ) ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_no_design_variables(testCase)
    x0 = [];
    if ~checkGradients(@(x) RBFKernel( ...
            testCase.TestData.X, ...
            testCase.TestData.Xp, ...
            testCase.TestData.sigma, ...
            testCase.TestData.sigmap, ...
            testCase.TestData.l ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_every_other_design_variables(testCase)
    Ns = length(testCase.TestData.sigma);    
    x0 = [testCase.TestData.sigma(:).', testCase.TestData.l(:).'];
    if ~checkGradients(@(x) RBFKernel( ...
            testCase.TestData.X, ...
            testCase.TestData.Xp, ...
            DesignVariable( ...
                x(1:Ns), ...
                1:Ns, ...
                length(x0) ...
            ), ...            
            testCase.TestData.sigmap, ...
            DesignVariable(x(Ns+1), Ns+1, length(x0)) ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end