function tests = test_nl_mvn_cov()
    tests = functiontests(localfunctions);
end

function setupOnce(testCase)
    N = randi([2,10]);
    testCase.TestData.x = unifrnd(-1,1, N, 1);
    testCase.TestData.mu = unifrnd(-1,1, N, 1);
    A = randn(N);
    testCase.TestData.C = A*A.' + 0.1*eye(N);
    testCase.TestData.options = optimoptions("fminunc", FiniteDifferenceType="central");

    timestamp = string(datetime("now", Format="uuuu-MM-dd_HH-mm-ss.SSS"));
    testCase.onFailure(@() logFailure(testCase, timestamp));
end

function teardownOnce(~)
end

function test_checkGradients_all_design_variables(testCase)
    N = numel(testCase.TestData.x);
    x0 = [testCase.TestData.x(:).', testCase.TestData.mu(:).', testCase.TestData.C(:).'];
    if ~checkGradients(@(x) format_output_for_checkGradients(@nl_mvn_cov,  ...
            DesignVariable(x(1:N).', (1:N).', length(x0)), ...
            DesignVariable(x(N+1:2*N).', (N+1:2*N).', length(x0)), ...
            DesignVariable( ...
                reshape(x(2*N+1:2*N+N*N), [N,N]), ...
                reshape(2*N+1:2*N+N*N, [N,N]), ...
                length(x0) ...
            ) ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_no_design_variables(testCase)
    x0 = [];
    if ~checkGradients(@(x) format_output_for_checkGradients(@nl_mvn_cov,  ...
            testCase.TestData.x, ...
            testCase.TestData.mu, ...
            testCase.TestData.C ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_every_other_design_variables(testCase)
    N = numel(testCase.TestData.x);
    x0 = [testCase.TestData.x(:).', testCase.TestData.C(:).'];
    if ~checkGradients(@(x) format_output_for_checkGradients(@nl_mvn_cov,  ...
            DesignVariable(x(1:N).', (1:N).', length(x0)), ...
            testCase.TestData.mu, ...
            DesignVariable( ...
                reshape(x(N+1:N+N*N), [N,N]), ...
                reshape(N+1:N+N*N, [N,N]), ...
                length(x0) ...
            ) ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_mvn_correctness(testCase)
    p = mvnpdf(testCase.TestData.x, testCase.TestData.mu, testCase.TestData.C);
    psi = format_output_for_checkGradients(@nl_mvn_cov, testCase.TestData.x, testCase.TestData.mu, testCase.TestData.C);
    testCase.verifyEqual(psi,-log(p), ...
    'AbsTol',1e-12, ...
    'RelTol',1e-12);
end