function tests = test_nl_mvn_prec()
    tests = functiontests(localfunctions);
end

function setupOnce(testCase)
    N = randi([2,10]);
    testCase.TestData.x = unifrnd(-1,1, N, 1);
    testCase.TestData.mu = unifrnd(-1,1, N, 1);
    A = randn(N);
    P = inv(A*A.' + 0.1*eye(N));
    testCase.TestData.P = 0.5*(P+P.');
    testCase.TestData.options = optimoptions("fminunc", FiniteDifferenceType="central");

    timestamp = string(datetime("now", Format="uuuu-MM-dd_HH-mm-ss.SSS"));
    testCase.onFailure(@() logFailure(testCase, timestamp));
end

function teardownOnce(~)
end

function test_checkGradients_all_design_variables(testCase)
    N = numel(testCase.TestData.x);
    x0 = [testCase.TestData.x(:).', testCase.TestData.mu(:).', testCase.TestData.P(:).'];
    if ~checkGradients(@(x) nl_mvn_prec( ...
            DesignVariable(x(1:N).', (1:N).', length(x0)), ...
            DesignVariable(x(N+1:2*N).', (N+1:2*N).', length(x0)), ...
            DesignVariable( ...
                reshape(x(2*N+1:2*N+N*N), [N,N]), ...
                reshape(2*N+1:2*N+N*N, [N,N]), ...
                length(x0) ...
            ) ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_no_design_variables(testCase)
    x0 = [];
    if ~checkGradients(@(x) nl_mvn_prec( ...
            testCase.TestData.x, ...
            testCase.TestData.mu, ...
            testCase.TestData.P ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_every_other_design_variables(testCase)
    N = numel(testCase.TestData.x);
    x0 = [testCase.TestData.x(:).', testCase.TestData.P(:).'];
    if ~checkGradients(@(x) nl_mvn_prec( ...
            DesignVariable(x(1:N).', (1:N).', length(x0)), ...
            testCase.TestData.mu, ...
            DesignVariable( ...
                reshape(x(N+1:N+N*N), [N,N]), ...
                reshape(N+1:N+N*N, [N,N]), ...
                length(x0) ...
            ) ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_mvn_correctness(testCase)
    N = numel(testCase.TestData.x);
    diff = testCase.TestData.x(:)-testCase.TestData.mu(:);
    p = (2*pi)^(-N/2) * sqrt(det(testCase.TestData.P)) * exp(-1/2*diff.'*testCase.TestData.P*diff);
    psi = nl_mvn_prec(testCase.TestData.x, testCase.TestData.mu, testCase.TestData.P);
    testCase.verifyEqual(psi,-log(p), ...
    'AbsTol',1e-12, ...
    'RelTol',1e-12);
    p = mvnpdf(testCase.TestData.x, testCase.TestData.mu, inv(testCase.TestData.P));
    testCase.verifyEqual(psi,-log(p), ...
    'AbsTol',1e-12, ...
    'RelTol',1e-12);
end