function tests = test_uniax2tensor()
    tests = functiontests(localfunctions);
end

function setupOnce(testCase)
    N = randi([4,7]);
    n = randi([5,8]);
    testCase.TestData.lnkperp_par = unifrnd(-5,5,N,2);
    testCase.TestData.v = unifrnd(-1,1,n,3);
    testCase.TestData.options = optimoptions("fminunc", FiniteDifferenceType="central");

    timestamp = string(datetime("now", Format="uuuu-MM-dd_HH-mm-ss.SSS"));
    testCase.onFailure(@() logFailure(testCase, timestamp));
end

function teardownOnce(~)
end

function test_match_auto_optimized(testCase)
    tensor = uniax2tensor(...
        testCase.TestData.lnkperp_par(:,1),...
        testCase.TestData.lnkperp_par(:,2),...
        testCase.TestData.v(:,1).',...
        testCase.TestData.v(:,2).',...
        testCase.TestData.v(:,3).'...
    );
    [k11,k12,k13,k22,k23,k33] = uniax2tensor_auto_optimized(...
        testCase.TestData.lnkperp_par(:,1),...
        testCase.TestData.lnkperp_par(:,2),...
        testCase.TestData.v(:,1).',...
        testCase.TestData.v(:,2).',...
        testCase.TestData.v(:,3).'...
    );
    
    if ~all(isequal(k11,tensor{1})) ...
    || ~all(isequal(k12,tensor{2})) ...
    || ~all(isequal(k13,tensor{3})) ...
    || ~all(isequal(k22,tensor{4})) ...
    || ~all(isequal(k23,tensor{5})) ...
    || ~all(isequal(k33,tensor{6}))
        error("uniax2tensor does not agree with uniax2tensor_auto_optimized")
    end
end

function test_checkGradients_all_design_variables(testCase)
    N = size(testCase.TestData.lnkperp_par,1);
    n = size(testCase.TestData.v,1);
    x0 = [testCase.TestData.lnkperp_par(:).', testCase.TestData.v(:).'];
    if ~checkGradients(@(x) obj_fun( ...
            DesignVariable(x(1:N)',(1:N)',length(x0)),...
            DesignVariable(x(N+1:2*N)',(N+1:2*N)',length(x0)),...
            DesignVariable(x(2*N+1:2*N+n),(2*N+1:2*N+n),length(x0)),...
            DesignVariable(x(2*N+n+1:2*N+2*n),(2*N+n+1:2*N+2*n),length(x0)),...
            DesignVariable(x(2*N+2*n+1:2*N+3*n),(2*N+2*n+1:2*N+3*n),length(x0))...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_no_design_variables(testCase)
    x0 = [];
    if ~checkGradients(@(x) obj_fun( ...
            testCase.TestData.lnkperp_par(:,1),...
            testCase.TestData.lnkperp_par(:,2),...
            testCase.TestData.v(:,1)',...
            testCase.TestData.v(:,2)',...
            testCase.TestData.v(:,3)'...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_all_lnkperp_par_design_variables(testCase)
    N = size(testCase.TestData.lnkperp_par,1);
    x0 = testCase.TestData.lnkperp_par(:).';
    if ~checkGradients(@(x) obj_fun( ...
            DesignVariable(x(1:N)',(1:N)',length(x0)),...
            DesignVariable(x(N+1:2*N)',(N+1:2*N)',length(x0)),...
            testCase.TestData.v(:,1)',...
            testCase.TestData.v(:,2)',...
            testCase.TestData.v(:,3)'...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_all_v_design_variables(testCase)
    n = size(testCase.TestData.v,1);
    x0 = testCase.TestData.v(:).';
    if ~checkGradients(@(x) obj_fun( ...
            testCase.TestData.lnkperp_par(:,1),...
            testCase.TestData.lnkperp_par(:,2),...
            DesignVariable(x(1:n),(1:n),length(x0)),...
            DesignVariable(x(n+1:2*n),(n+1:2*n),length(x0)),...
            DesignVariable(x(2*n+1:3*n),(2*n+1:3*n),length(x0))...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_every_other_design_variables(testCase)
    N = size(testCase.TestData.lnkperp_par,1);
    n = size(testCase.TestData.v,1);
    x0 = [ ...
        testCase.TestData.lnkperp_par(:,1).', ...
        testCase.TestData.v(:,1).', ...
        testCase.TestData.v(:,3).' ...
    ];
    if ~checkGradients(@(x) obj_fun( ...
            DesignVariable(x(1:N)',(1:N)',length(x0)),...
            testCase.TestData.lnkperp_par(:,2),...
            DesignVariable(x(N+1:N+n),(N+1:N+n),length(x0)),...
            testCase.TestData.v(:,2)',...
            DesignVariable(x(N+n+1:N+2*n),(N+n+1:N+2*n),length(x0))...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function [out, Jac] = obj_fun(lnkperp,lnkpar,v1,v2,v3)
    if nargout < 2
        tensor = uniax2tensor(lnkperp,lnkpar,v1,v2,v3);
    else
        [tensor, Jac] = uniax2tensor(lnkperp,lnkpar,v1,v2,v3);
    end
    out = horzcat(tensor{:});
    out = out(:);
end