function tests = test_principal2tensor()
    tests = functiontests(localfunctions);
end

function setupOnce(testCase)
    N = randi([4,7]);
    n = randi([5,8]);
    testCase.TestData.lnkp = unifrnd(-5,5,N,3);
    testCase.TestData.q = unifrnd(-1,1,n,4);
    testCase.TestData.options = optimoptions("fminunc", FiniteDifferenceType="central");
end

function teardownOnce(~)
end

function test_match_auto_optimized(testCase)
    tensor = principal2tensor(...
        testCase.TestData.lnkp(:,1),...
        testCase.TestData.lnkp(:,2),...
        testCase.TestData.lnkp(:,3),...
        testCase.TestData.q(:,1).',...
        testCase.TestData.q(:,2).',...
        testCase.TestData.q(:,3).',...
        testCase.TestData.q(:,4).'...
    );
    [k11,k12,k13,k22,k23,k33] = principal2tensor_auto_optimized(...
        testCase.TestData.lnkp(:,1),...
        testCase.TestData.lnkp(:,2),...
        testCase.TestData.lnkp(:,3),...
        testCase.TestData.q(:,1).',...
        testCase.TestData.q(:,2).',...
        testCase.TestData.q(:,3).',...
        testCase.TestData.q(:,4).'...
    );
    
    if ~all(isequal(k11,tensor{1})) ...
    || ~all(isequal(k12,tensor{2})) ...
    || ~all(isequal(k13,tensor{3})) ...
    || ~all(isequal(k22,tensor{4})) ...
    || ~all(isequal(k23,tensor{5})) ...
    || ~all(isequal(k33,tensor{6}))
        error("principal2tensor does not agree with principal2tensor_auto_optimized")
    end
end

function test_checkGradients_all_design_variables(testCase)
    N = size(testCase.TestData.lnkp,1);
    n = size(testCase.TestData.q,1);
    x0 = [testCase.TestData.lnkp(:).', testCase.TestData.q(:).'];
    if ~checkGradients(@(x) obj_fun( ...
            DesignVariable(x(1:N)',(1:N)',length(x0)),...
            DesignVariable(x(N+1:2*N)',(N+1:2*N)',length(x0)),...
            DesignVariable(x(2*N+1:3*N)',(2*N+1:3*N)',length(x0)),...
            DesignVariable(x(3*N+1:3*N+n),(3*N+1:3*N+n),length(x0)),...
            DesignVariable(x(3*N+n+1:3*N+2*n),(3*N+n+1:3*N+2*n),length(x0)),...
            DesignVariable(x(3*N+2*n+1:3*N+3*n),(3*N+2*n+1:3*N+3*n),length(x0)),...
            DesignVariable(x(3*N+3*n+1:3*N+4*n),(3*N+3*n+1:3*N+4*n),length(x0))...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_no_design_variables(testCase)
    x0 = [];
    if ~checkGradients(@(x) obj_fun( ...
            testCase.TestData.lnkp(:,1),...
            testCase.TestData.lnkp(:,2),...
            testCase.TestData.lnkp(:,3),...
            testCase.TestData.q(:,1)',...
            testCase.TestData.q(:,2)',...
            testCase.TestData.q(:,3)',...
            testCase.TestData.q(:,4)'...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_all_lnkp_design_variables(testCase)
    N = size(testCase.TestData.lnkp,1);
    x0 = testCase.TestData.lnkp(:).';
    if ~checkGradients(@(x) obj_fun( ...
            DesignVariable(x(1:N)',(1:N)',length(x0)),...
            DesignVariable(x(N+1:2*N)',(N+1:2*N)',length(x0)),...
            DesignVariable(x(2*N+1:3*N)',(2*N+1:3*N)',length(x0)),...
            testCase.TestData.q(:,1)',...
            testCase.TestData.q(:,2)',...
            testCase.TestData.q(:,3)',...
            testCase.TestData.q(:,4)'...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_all_q_design_variables(testCase)
    n = size(testCase.TestData.q,1);
    x0 = testCase.TestData.q(:).';
    if ~checkGradients(@(x) obj_fun( ...
            testCase.TestData.lnkp(:,1),...
            testCase.TestData.lnkp(:,2),...
            testCase.TestData.lnkp(:,3),...
            DesignVariable(x(1:n),(1:n),length(x0)),...
            DesignVariable(x(n+1:2*n),(n+1:2*n),length(x0)),...
            DesignVariable(x(2*n+1:3*n),(2*n+1:3*n),length(x0)),...
            DesignVariable(x(3*n+1:4*n),(3*n+1:4*n),length(x0))...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_every_other_design_variables(testCase)
    N = size(testCase.TestData.lnkp,1);
    n = size(testCase.TestData.q,1);
    x0 = [ ...
        testCase.TestData.lnkp(:,1).', ...
        testCase.TestData.lnkp(:,3).', ...
        testCase.TestData.q(:,2).', ...
        testCase.TestData.q(:,4).' ...
    ];
    if ~checkGradients(@(x) obj_fun( ...
            DesignVariable(x(1:N)',(1:N)',length(x0)),...
            testCase.TestData.lnkp(:,2),...
            DesignVariable(x(N+1:2*N)',(N+1:2*N)',length(x0)),...
            testCase.TestData.q(:,1)',...
            DesignVariable(x(2*N+1:2*N+n),(2*N+1:2*N+n),length(x0)),...
            testCase.TestData.q(:,3)',...
            DesignVariable(x(2*N+n+1:2*N+2*n),(2*N+n+1:2*N+2*n),length(x0))...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function [out, Jac] = obj_fun(lnkp1,lnkp2,lnkp3,q1,q2,q3,q4)
    if nargout < 2
        tensor = principal2tensor(lnkp1,lnkp2,lnkp3,q1,q2,q3,q4);
    else
        [tensor, Jac] = principal2tensor(lnkp1,lnkp2,lnkp3,q1,q2,q3,q4);
    end
    out = horzcat(tensor{:});
    out = out(:);
end