function tests = test_tensor2tensor()
    tests = functiontests(localfunctions);
end

function setupOnce(testCase)
    N = randi([4,7]);
    n = randi([5,8]);
    testCase.TestData.k11 = unifrnd(0.1,500,N,n);
    testCase.TestData.k12 = unifrnd(0.1,500,N,n);
    testCase.TestData.k13 = unifrnd(0.1,500,N,n);
    testCase.TestData.k22 = unifrnd(0.1,500,N,n);
    testCase.TestData.k23 = unifrnd(0.1,500,N,n);
    testCase.TestData.k33 = unifrnd(0.1,500,N,n);
    testCase.TestData.options = optimoptions("fminunc", FiniteDifferenceType="central");

    timestamp = string(datetime("now", Format="uuuu-MM-dd_HH-mm-ss.SSS"));
    testCase.onFailure(@() logFailure(testCase, timestamp));
end

function teardownOnce(~)
end

function test_checkGradients_all_design_variables(testCase)
    [N,n] = size(testCase.TestData.k11);
    x0 = [
        testCase.TestData.k11(:).',...
        testCase.TestData.k12(:).',...
        testCase.TestData.k13(:).',...
        testCase.TestData.k22(:).',...
        testCase.TestData.k23(:).',...
        testCase.TestData.k33(:).'...
    ];
    if ~checkGradients(@(x) obj_fun( ...
            DesignVariable(reshape(x(0*n*N+1:1*n*N),N,n),reshape((0*n*N+1:1*n*N),N,n),length(x0)),...
            DesignVariable(reshape(x(1*n*N+1:2*n*N),N,n),reshape((1*n*N+1:2*n*N),N,n),length(x0)),...
            DesignVariable(reshape(x(2*n*N+1:3*n*N),N,n),reshape((2*n*N+1:3*n*N),N,n),length(x0)),...
            DesignVariable(reshape(x(3*n*N+1:4*n*N),N,n),reshape((3*n*N+1:4*n*N),N,n),length(x0)),...
            DesignVariable(reshape(x(4*n*N+1:5*n*N),N,n),reshape((4*n*N+1:5*n*N),N,n),length(x0)),...
            DesignVariable(reshape(x(5*n*N+1:6*n*N),N,n),reshape((5*n*N+1:6*n*N),N,n),length(x0))...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_no_design_variables(testCase)
    x0 = [];
    if ~checkGradients(@(x) obj_fun( ...
            testCase.TestData.k11,...
            testCase.TestData.k12,...
            testCase.TestData.k13,...
            testCase.TestData.k22,...
            testCase.TestData.k23,...
            testCase.TestData.k33...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_every_other_design_variables(testCase)
    [N,n] = size(testCase.TestData.k11);
    x0 = [
        testCase.TestData.k11(:).',...
        testCase.TestData.k13(:).',...
        testCase.TestData.k23(:).',...
    ];
    if ~checkGradients(@(x) obj_fun( ...
            DesignVariable(reshape(x(0*n*N+1:1*n*N),N,n),reshape((0*n*N+1:1*n*N),N,n),length(x0)),...
            testCase.TestData.k12,...
            DesignVariable(reshape(x(1*n*N+1:2*n*N),N,n),reshape((1*n*N+1:2*n*N),N,n),length(x0)),...
            testCase.TestData.k22,...
            DesignVariable(reshape(x(2*n*N+1:3*n*N),N,n),reshape((2*n*N+1:3*n*N),N,n),length(x0)),...
            testCase.TestData.k33...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function [out, Jac] = obj_fun(k11, k12, k13, k22, k23, k33)
    if nargout < 2
        tensor = tensor2tensor(k11, k12, k13, k22, k23, k33);
    else
        [tensor, Jac] = tensor2tensor(k11, k12, k13, k22, k23, k33);
    end
    out = horzcat(tensor{:});
    out = out(:);
end