function tests = test_nln()
    tests = functiontests(localfunctions);
end

function setupOnce(testCase)
    N = randi([1,5]); n = randi([1,5]); Nf = randi([1,5]); Nprobe = randi([1,5]);
    testCase.TestData.x = unifrnd(-1,1);
    testCase.TestData.mu = unifrnd(-1,1,N,n,Nf,Nprobe);
    testCase.TestData.sigma = unifrnd(1,2,N,n,Nf,Nprobe);
    testCase.TestData.options = optimoptions("fminunc", FiniteDifferenceType="central");

    timestamp = string(datetime("now", Format="uuuu-MM-dd_HH-mm-ss.SSS"));
    testCase.onFailure(@() logFailure(testCase, timestamp));
end

function teardownOnce(~)
end

function test_checkGradients_all_design_variables(testCase)
    [N,n,Nf,Nprobe] = size(testCase.TestData.mu);
    x0 = [testCase.TestData.x(:).', testCase.TestData.mu(:).', testCase.TestData.sigma(:).'];
    if ~checkGradients(@(x) format_output_for_checkGradients(@nln, DesignVariable(x(1), 1, length(x0)), ...
            DesignVariable( ...
                reshape(x(2:N*n*Nf*Nprobe+1), [N,n,Nf,Nprobe]), ...
                reshape(2:N*n*Nf*Nprobe+1, [N,n,Nf,Nprobe]), ...
                length(x0) ...
            ), ...
            DesignVariable( ...
                reshape(x(N*n*Nf*Nprobe+2:2*N*n*Nf*Nprobe+1), [N,n,Nf,Nprobe]), ...
                reshape(N*n*Nf*Nprobe+2:2*N*n*Nf*Nprobe+1, [N,n,Nf,Nprobe]), ...
                length(x0) ...
            ) ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_no_design_variables(testCase)
    x0 = [];
    if ~checkGradients(@(x) format_output_for_checkGradients(@nln,  ...
            testCase.TestData.x, ...
            testCase.TestData.mu, ...
            testCase.TestData.sigma ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_every_other_design_variables(testCase)
    [N,n,Nf,Nprobe] = size(testCase.TestData.mu);
    x0 = [testCase.TestData.x(:).', testCase.TestData.sigma(:).'];
    if ~checkGradients(@(x) format_output_for_checkGradients(@nln, DesignVariable(x(1), 1, length(x0)), ...
            testCase.TestData.mu, ...
            DesignVariable( ...
                reshape(x(2:N*n*Nf*Nprobe+1), [N,n,Nf,Nprobe]), ...
                reshape(2:N*n*Nf*Nprobe+1, [N,n,Nf,Nprobe]), ...
                length(x0) ...
            ) ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end