function tests = test_nll_phase()
    tests = functiontests(localfunctions);
end

function setupOnce(testCase)
    N = randi([1,5]); n = randi([1,5]); Nf = randi([1,5]); Nprobe = randi([1,5]);
    testCase.TestData.phi_pred = unifrnd(-pi,pi,N,n,Nf,Nprobe);
    testCase.TestData.phi_obs = unifrnd(-pi,pi,N,n,Nf,Nprobe);
    testCase.TestData.kT = unifrnd(1,1000,1,1);
    testCase.TestData.kD = unifrnd(1,1000,N,n,Nf,Nprobe);
    testCase.TestData.options = optimoptions("fminunc", FiniteDifferenceType="central");

    timestamp = string(datetime("now", Format="uuuu-MM-dd_HH-mm-ss.SSS"));
    testCase.onFailure(@() logFailure(testCase, timestamp));
end

function teardownOnce(~)
end

function test_checkGradients_all_design_variables(testCase)
    [N,n,Nf,Nprobe] = size(testCase.TestData.phi_pred);
    x0 = [testCase.TestData.phi_pred(:).', testCase.TestData.phi_obs(:).', testCase.TestData.kT(:).', testCase.TestData.kD(:).'];
    if ~checkGradients(@(x) nll_phase( ...
            DesignVariable( ...
                reshape(x(1:N*n*Nf*Nprobe), [N,n,Nf,Nprobe]), ...
                reshape(1:N*n*Nf*Nprobe, [N,n,Nf,Nprobe]), ...
                length(x0) ...
            ), ...
            DesignVariable( ...
                reshape(x(N*n*Nf*Nprobe+1:2*N*n*Nf*Nprobe), [N,n,Nf,Nprobe]), ...
                reshape(N*n*Nf*Nprobe+1:2*N*n*Nf*Nprobe, [N,n,Nf,Nprobe]), ...
                length(x0) ...
            ), ...
            DesignVariable(x(2*N*n*Nf*Nprobe+1), 2*N*n*Nf*Nprobe+1, length(x0)), ...
            DesignVariable( ...
                reshape(x(2*N*n*Nf*Nprobe+2:3*N*n*Nf*Nprobe+1), [N,n,Nf,Nprobe]), ...
                reshape(2*N*n*Nf*Nprobe+2:3*N*n*Nf*Nprobe+1, [N,n,Nf,Nprobe]), ...
                length(x0) ...
            ) ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_no_design_variables(testCase)
    x0 = [];
    if ~checkGradients(@(x) nll_phase( ...
            testCase.TestData.phi_pred, ...
            testCase.TestData.phi_obs, ...
            testCase.TestData.kT, ...
            testCase.TestData.kD ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end

function test_checkGradients_every_other_design_variables(testCase)
    [N,n,Nf,Nprobe] = size(testCase.TestData.phi_pred);
    x0 = [testCase.TestData.phi_pred(:).', testCase.TestData.kT(:).'];
    if ~checkGradients(@(x) nll_phase( ...
            DesignVariable( ...
                reshape(x(1:N*n*Nf*Nprobe), [N,n,Nf,Nprobe]), ...
                reshape(1:N*n*Nf*Nprobe, [N,n,Nf,Nprobe]), ...
                length(x0) ...
            ), ...
            testCase.TestData.phi_obs, ...
            DesignVariable(x(N*n*Nf*Nprobe+1), N*n*Nf*Nprobe+1, length(x0)), ...
            testCase.TestData.kD ...
        ), x0, testCase.TestData.options, Display="on")
        error("checkGradients Failed!")
    end
end