function [k11,k12,k13,k22,k23,k33,dk11_dlnkp1,dk12_dlnkp1,dk13_dlnkp1,dk22_dlnkp1,dk23_dlnkp1,dk33_dlnkp1,dk11_dlnkp2,dk12_dlnkp2,dk13_dlnkp2,dk22_dlnkp2,dk23_dlnkp2,dk33_dlnkp2,dk11_dlnkp3,dk12_dlnkp3,dk13_dlnkp3,dk22_dlnkp3,dk23_dlnkp3,dk33_dlnkp3,dk11_dq1,dk12_dq1,dk13_dq1,dk22_dq1,dk23_dq1,dk33_dq1,dk11_dq2,dk12_dq2,dk13_dq2,dk22_dq2,dk23_dq2,dk33_dq2,dk11_dq3,dk12_dq3,dk13_dq3,dk22_dq3,dk23_dq3,dk33_dq3,dk11_dq4,dk12_dq4,dk13_dq4,dk22_dq4,dk23_dq4,dk33_dq4] = principal2tensor_auto_optimized(lnkp1,lnkp2,lnkp3,q1,q2,q3,q4)
%PRINCIPAL2TENSOR_AUTO_OPTIMIZED
%    [K11,K12,K13,K22,K23,K33,DK11_DLNKP1,DK12_DLNKP1,DK13_DLNKP1,DK22_DLNKP1,DK23_DLNKP1,DK33_DLNKP1,DK11_DLNKP2,DK12_DLNKP2,DK13_DLNKP2,DK22_DLNKP2,DK23_DLNKP2,DK33_DLNKP2,DK11_DLNKP3,DK12_DLNKP3,DK13_DLNKP3,DK22_DLNKP3,DK23_DLNKP3,DK33_DLNKP3,DK11_DQ1,DK12_DQ1,DK13_DQ1,DK22_DQ1,DK23_DQ1,DK33_DQ1,DK11_DQ2,DK12_DQ2,DK13_DQ2,DK22_DQ2,DK23_DQ2,DK33_DQ2,DK11_DQ3,DK12_DQ3,DK13_DQ3,DK22_DQ3,DK23_DQ3,DK33_DQ3,DK11_DQ4,DK12_DQ4,DK13_DQ4,DK22_DQ4,DK23_DQ4,DK33_DQ4] = PRINCIPAL2TENSOR_AUTO_OPTIMIZED(LNKP1,LNKP2,LNKP3,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    29-Aug-2026 14:38:44

t2 = exp(lnkp1);
t3 = exp(lnkp2);
t4 = exp(lnkp3);
t5 = q1.^2;
t6 = q2.^2;
t7 = q3.^2;
t8 = q4.^2;
t9 = q1.*q2.*2.0;
t10 = q1.*q3.*2.0;
t11 = q1.*q4.*2.0;
t12 = q2.*q3.*2.0;
t13 = q2.*q4.*2.0;
t14 = q3.*q4.*2.0;
t15 = t5.*2.0;
t16 = t6.*2.0;
t17 = t7.*2.0;
t18 = t8.*2.0;
t19 = -t12;
t20 = -t13;
t21 = -t14;
t22 = t9+t14;
t23 = t10+t13;
t24 = t11+t12;
t25 = t9+t21;
t26 = t10+t20;
t27 = t11+t19;
t28 = t22.^2;
t29 = t23.^2;
t30 = t24.^2;
t34 = t15+t16-1.0;
t35 = t15+t17-1.0;
t36 = t15+t18-1.0;
t40 = q1.*t2.*t24.*4.0;
t41 = q1.*t3.*t22.*4.0;
t42 = q2.*t2.*t24.*4.0;
t43 = q1.*t4.*t23.*4.0;
t44 = q3.*t3.*t22.*4.0;
t45 = q4.*t4.*t23.*4.0;
t31 = t25.^2;
t32 = t26.^2;
t33 = t27.^2;
t37 = t2.*t30;
t38 = t3.*t28;
t39 = t4.*t29;
t46 = t34.^2;
t47 = t35.^2;
t48 = t36.^2;
t52 = q1.*t2.*t26.*4.0;
t53 = q1.*t3.*t27.*4.0;
t54 = q2.*t2.*t26.*4.0;
t55 = q1.*t4.*t25.*4.0;
t56 = q3.*t3.*t27.*4.0;
t57 = q4.*t4.*t25.*4.0;
t64 = q1.*t2.*t34.*2.0;
t65 = q2.*t2.*t34.*2.0;
t66 = q1.*t3.*t35.*2.0;
t67 = q3.*t2.*t34.*2.0;
t68 = q2.*t3.*t35.*2.0;
t69 = q4.*t2.*t34.*2.0;
t70 = q1.*t4.*t36.*2.0;
t71 = q3.*t3.*t35.*2.0;
t72 = q2.*t4.*t36.*2.0;
t73 = q4.*t3.*t35.*2.0;
t74 = q3.*t4.*t36.*2.0;
t75 = q4.*t4.*t36.*2.0;
t76 = t2.*t24.*t26;
t77 = t3.*t22.*t27;
t78 = t4.*t23.*t25;
t82 = t2.*t24.*t34;
t83 = t3.*t22.*t35;
t84 = t4.*t23.*t36;
t85 = t2.*t26.*t34;
t86 = t3.*t27.*t35;
t87 = t4.*t25.*t36;
t49 = t2.*t32;
t50 = t3.*t33;
t51 = t4.*t31;
t58 = -t54;
t59 = -t56;
t60 = -t57;
t61 = t2.*t46;
k11 = t39+t50+t61;
if nargout > 1
    t62 = t3.*t47;
    t63 = t4.*t48;
    t79 = -t76;
    t80 = -t77;
    t81 = -t78;
    t88 = -t85;
    t89 = -t86;
    k12 = t81+t82+t89;
end
if nargout > 2
    k13 = t80+t84+t88;
end
if nargout > 3
    k22 = t37+t51+t62;
end
if nargout > 4
    t90 = -t87;
    k23 = t79+t83+t90;
end
if nargout > 5
    k33 = t38+t49+t63;
end
if nargout > 6
    dk11_dlnkp1 = t61;
end
if nargout > 7
    dk12_dlnkp1 = t82;
end
if nargout > 8
    dk13_dlnkp1 = t88;
end
if nargout > 9
    dk22_dlnkp1 = t37;
end
if nargout > 10
    dk23_dlnkp1 = t79;
end
if nargout > 11
    dk33_dlnkp1 = t49;
end
if nargout > 12
    dk11_dlnkp2 = t50;
end
if nargout > 13
    dk12_dlnkp2 = t89;
end
if nargout > 14
    dk13_dlnkp2 = t80;
end
if nargout > 15
    dk22_dlnkp2 = t62;
end
if nargout > 16
    dk23_dlnkp2 = t83;
end
if nargout > 17
    dk33_dlnkp2 = t38;
end
if nargout > 18
    dk11_dlnkp3 = t39;
end
if nargout > 19
    dk12_dlnkp3 = t81;
end
if nargout > 20
    dk13_dlnkp3 = t84;
end
if nargout > 21
    dk22_dlnkp3 = t51;
end
if nargout > 22
    dk23_dlnkp3 = t90;
end
if nargout > 23
    dk33_dlnkp3 = t63;
end
if nargout > 24
    dk11_dq1 = q3.*t4.*t23.*4.0+q4.*t3.*t27.*4.0+q1.*t2.*t34.*8.0;
end
if nargout > 25
    dk12_dq1 = t40-t53+t69-t73-q2.*t4.*t23.*2.0-q3.*t4.*t25.*2.0;
end
if nargout > 26
    dk13_dq1 = t43-t52-t67+t74-q4.*t3.*t22.*2.0-q2.*t3.*t27.*2.0;
end
if nargout > 27
    dk22_dq1 = q4.*t2.*t24.*4.0+q2.*t4.*t25.*4.0+q1.*t3.*t35.*8.0;
end
if nargout > 28
    dk23_dq1 = t41-t55+t68-t72-q3.*t2.*t24.*2.0-q4.*t2.*t26.*2.0;
end
if nargout > 29
    dk33_dq1 = q2.*t3.*t22.*4.0+q3.*t2.*t26.*4.0+q1.*t4.*t36.*8.0;
end
if nargout > 30
    dk11_dq2 = t45+t59+q2.*t2.*t34.*8.0;
end
if nargout > 31
    dk12_dq2 = t42+t67+t71-q1.*t4.*t23.*2.0-q4.*t4.*t25.*2.0;
end
if nargout > 32
    dk13_dq2 = t58+t69+t75+q3.*t3.*t22.*2.0-q1.*t3.*t27.*2.0;
end
if nargout > 33
    dk22_dq2 = t55+q3.*t2.*t24.*4.0;
end
if nargout > 34
    dk23_dq2 = t66-t70+q4.*t2.*t24.*2.0-q3.*t2.*t26.*2.0;
end
if nargout > 35
    dk33_dq2 = t41-q4.*t2.*t26.*4.0;
end
if nargout > 36
    dk11_dq3 = t43-q2.*t3.*t27.*4.0;
end
if nargout > 37
    dk12_dq3 = t59+t65+t68-q1.*t4.*t25.*2.0+q4.*t4.*t23.*2.0;
end
if nargout > 38
    dk13_dq3 = -t64+t70+q2.*t3.*t22.*2.0-q4.*t3.*t27.*2.0;
end
if nargout > 39
    dk22_dq3 = t42+t60+q3.*t3.*t35.*8.0;
end
if nargout > 40
    dk23_dq3 = t44+t73+t75-q1.*t2.*t24.*2.0-q2.*t2.*t26.*2.0;
end
if nargout > 41
    dk33_dq3 = t52+q4.*t3.*t22.*4.0;
end
if nargout > 42
    dk11_dq4 = t53+q2.*t4.*t23.*4.0;
end
if nargout > 43
    dk12_dq4 = t64-t66+q3.*t4.*t23.*2.0-q2.*t4.*t25.*2.0;
end
if nargout > 44
    dk13_dq4 = t45+t65+t72-q1.*t3.*t22.*2.0-q3.*t3.*t27.*2.0;
end
if nargout > 45
    dk22_dq4 = t40-q3.*t4.*t25.*4.0;
end
if nargout > 46
    dk23_dq4 = t60+t71+t74+q2.*t2.*t24.*2.0-q1.*t2.*t26.*2.0;
end
if nargout > 47
    dk33_dq4 = t44+t58+q4.*t4.*t36.*8.0;
end
end
